alpha:
  .settings:
    no_script_name:         true
    logging_enabled:        false

alpha_dev:
  .settings:
    error_reporting:        <?php echo (E_ALL & ~E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

live:
  .settings:
    csrf_secret:            6c4a1a381267O49d9cd43528e3b4549b55a0e0b6
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL & ~E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

live_dev:
  .settings:
    web_debug:              true
    cache:                  false
    no_script_name:         true
    etag:                   false

debug:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

cache:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  true
    web_debug:              true
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:      default
    error_404_action:      error404
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            6c4a1a381267049d9cd43528e3b4549b55a0e0b6

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    default_culture:        ru

    standard_helpers:
      - Cache
      - Date
      - myPartial
      - myUrl

    login_module:           guard
    login_action:           signin

    secure_module:          guard
    secure_action:          secure

    cache:                  true