# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    yandex-verification: 623bb356993d4993
    viewport:	   width=960
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow


  stylesheets:
#    - normalize.css
#    - jquery-ui-custom/jquery-ui-custom.css
#    - colorbox/colorbox.css
#    - jquery.autocomplete.css
#    - main.css
    - global.css
#    - skin/inner.css?2012-10-01
#    - jquery-ui-1.8.20.custom.css
#    - font.css
#    - skin/main.css
#    - navy.css

  javascripts:
#    - jquery-1.6.4.min.js
#    - bigjquery.min.js
#    - jquery.ui.touch-punch.min.js
    #ivn- jquery-ui-1.8.16.custom.min.js
    #ivn- jquery.effects.core.js
    #ivn- jquery.effects.transfer.js
    #ivn- jquery.lightbox_me.js
    #ivn- prettyCheckboxes.js
    #ivn- jcookies.js
    #ivn- jquery.jshowoff.min.js
    #ivn- typewriter.js
    #ivn- custom-form-elements.js
    #ivn- jquery.form.js
    #ivn- jquery.timers.js
    #ivn- jquery.raty.js
    #ivn- jquery.scrollto.js
#    - main.js
#    - app.auth.js
#    - mechanics.js
#    - dash.js
#    - app.search.js
#    - app.region.js

  has_layout:     true
  layout:         layout

